var server = {
  local: "http://localhost:8002/",
  prod:"http://roteirizador.centrique.net:8002/"
}

var heightServer = {
  local: "http://localhost:8002/",
  prod:"http://roteirizador.centrique.net:8002/"
}

//Add your own tokens for testing
var prodToken = ""
